// Copyright © 2024 Snap, Inc. All rights reserved.

import CryptoKit
import DeviceCheck
import Foundation

/// Protocol abstracting key storage so that it can be configured and/or mocked for testing purposes
protocol AuthRepository: Sendable {
    /**
     The full application identifier, generated by concatenating the 10 letter team ID with the bundle id
     */
    var applicationId: String? { get }

    /**
     A possibly-empty list of private signing keys that we have previously attested to the device.
     */
    var signingPrivateKeys: [any P256SigningKey] { get async }

    /**
     Called to generate a new signing key when requested by the handshake.

     Returns the key, along with a closure that can be optionally used to persist the key for later use.
     When possible, return keys backed by the secure enclave. See SecureEnclave.P256.Signing.PrivateKey for details.
     */
    func generateNewSigningKey() async throws -> (key: any P256SigningKey, saveOperation: @Sendable () async -> Void)

    /**
     A possibly-empty list of x9.63-encoded ECC public signing keys that should be accepted without requiring an attestation statement from the device
     */
    var x963EncodedPretrustedPublicKeys: [Data] { get async }

    /**
     Called after the handshake completes if the peer attests a new ECC public signing key with the x9.63-encoded data of that key.
     */
    func saveX963EncodedPretrustedPublicKey(_ data: Data) async

    /**
     Get the list of DER-encoded X.509 trusted root certificates to accept for the current connection
     */
    var derEncodedRootCertData: [Data] { get async }
}

@SecurityActor
extension AuthRepository {
    /**
     Loads all compatible auth providers

     Currently supports Pretrusted, Device Check, and Unauthenticated providers
     */
    func loadAuthProviders(isClient: Bool) async -> [any HandshakeAuthProvider] {
        var ret = [any HandshakeAuthProvider]()

        if SecureEnclave.isAvailable {
            
            for signingKey in await signingPrivateKeys {
                // ret.append(PretrustedAuthProvider(key: signingKey, isClient: isClient))
            }

            if DCAppAttestService.shared.isSupported {
                ret.append(DeviceCheckAuthProvider(authRepository: self, isClient: isClient))
            }
        }

//        #if DEBUG
//            if let applicationId {
//                ret.append(UnauthenticatedAuthProvider(identity: applicationId))
//            }
//        #endif

        return ret
    }
    /**
     Loads all compatible auth providers

     Currently supports Pretrusted, X509 Certificate, and Unauthenticated providers
     */
    func loadAuthVerifiers(isClient: Bool, acceptUnfusedSpectacles: Bool) async -> [any HandshakeAuthVerifier] {
        var ret = [any HandshakeAuthVerifier]()

        for keyData in await x963EncodedPretrustedPublicKeys {
            if let verifier = try? PretrustedAuthVerifier(peerPublicKey: keyData, isClient: isClient) {
                ret.append(verifier)
            }
        }

        let rootCerts = await derEncodedRootCertData.compactMap { certData in
            SecCertificateCreateWithData(kCFAllocatorDefault, certData as CFData)
        }
        if !rootCerts.isEmpty {
            ret.append(X509CertAuthVerifier(
                authRepository: self,
                skipEnvironmentCheck: acceptUnfusedSpectacles,
                rootCerts: rootCerts,
                isClient: isClient
            ))
        }

//        #if DEBUG
//            ret.append(UnauthenticatedAuthVerifier(identity: nil))
//        #endif

        return ret
    }
}
